"""correcao do campo pudated_at

Revision ID: 6aebaece3859
Revises: d0d5de2f00d6
Create Date: 2025-01-09 19:25:20.073991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aebaece3859'
down_revision: Union[str, None] = 'd0d5de2f00d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column(
    'updated_at', sa.DateTime(), 
    server_default=sa.text('CURRENT_TIMESTAMP'), 
    nullable=False)
)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
